### ISSUE TITLE
TeamSystem IDP missing

### ISSUE THREAD

**Issue by hello96** [dej611/spid-react-button#105]
Hi there!
First of all, thank you for sharing such a useful component! :)
This morning I submitted my Service Provider Registration to AgID and they told me that TeamSystem IDP has to be shown among the available Identity Providers.
I might be wrong, but as far as I can see in the repo it has not been added yet.

I would like to contribute if no one else is already working on this. Let me know :)

**Comment by dej611** [comment]
Hi, sorry for the late reply.
> I would like to contribute if no one else is already working on this. Let me know :)

That would be great, feel free to submit a PR! :)

**Comment by dej611** [comment]
@hello96 while doing some work on the providers list I've included also the new `TeamSystem ID` meta + assets in the  PR.
