### ISSUE TITLE
[a11y] WAI Aria pratices for dialog

### ISSUE THREAD

**Issue by gdorsi** [dej611/spid-react-button#30]
Hello!

First, thanks for publishing this project.

The of sharing FOSS projects in our local community could become a very nice way to grow together.

I think that would be very interesting to try to be fully compliant with the WAI aria pratices in order to improve the accessibilty of the component.

We could start implementing the [WAI aria guidelines for the dialog](https://www.w3.org/TR/wai-aria-practices-1.2/#dialog_modal).

A good example that we could follow is [the Reach UI dialog](https://reach.tech/dialog/).

What do you think?

**Comment by dej611** [comment]
Seems like a good idea! 👍  Will look into that
